project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
    - text: "In Class Excercise"
      menu:
        - text: "In Class Ex1"
          href: "Hands-on_EX01/Hands-on_Ex01/hands-on_Ex01.html"
        - text: "In Class Ex3"
          href: "In-Class_Ex03/In_Class03.html"
        - text: "In Class Ex4"
          href: "In-Class_EX04/In_Class04.html"
        - text: "In Class Ex5a"
          href: "In-Class_EX05/In_Class05.html"
        - text: "In Class Ex5b"
          href: "In-Class_EX05/In_Class05b.html"
    - text: "Take-home Excercise"
      menu:
        - text: "Takehome Ex 1"
          href: "Takehome_Ex/Takehome_Ex_01/takehome_Ex_01.html"
        - text: "Takehome Ex 2"
          href: "Takehome_Ex/Takehome_Ex_02/takehome_Ex_02.html"
        - text: "Takehome Ex 3"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

