---
title: "InClass Ex 3"
author: "Aruiana"
date: 28 Jan 2023
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval:true
  warning:false
format: html
editor: visual
---

Getting Started

Install and launch R packages

The code chunk below uses p_load() of pacman package to check if tidyverse and ggiraph packages are installed in the computer.

```{r}
pacman::p_load(ggiraph, tidyverse)
```

Importing the data

```{r}
#| echo: false
  exam_data <- read_csv("data/Exam_data.csv", show_col_types = FALSE)
```

Plotting a simple bar chart

```{r}
#| echo: false 
ggplot(data = exam_data,
       aes(x = RACE, fill = RACE)) +
  geom_bar() + scale_fill_manual("legend", values = c("Chinese" = "indianred1", "Indian" = "orange", "Malay" = "royalblue3", "Others" = "green"))
```

```{r}
p <- ggplot(data=exam_data, 
       aes(x = MATHS)) +
  geom_dotplot_interactive(
    aes(tooltip = ID),
    stackgroups = TRUE, 
    binwidth = 1, 
    method = "histodot") +
  scale_y_continuous(NULL, 
                     breaks = NULL)
girafe(
  ggobj = p,
  width_svg = 6,
  height_svg = 6*0.618
)
```
