---
title: "Take Home Ex 3"
author: "Aruiana"
date: 5 Feb 2023
date-modified: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
editor: visual
---

```{r}
pacman::p_load(tidyverse, plotly, crosstalk, DT, ggdist, gganimate, ggstatsplot)

HDB <- read_csv(("data/HDB.csv"))

#Create addtional data on price per sqm
HDB$price_per_sqm <- (HDB$resale_price / HDB$floor_area_sqm)


```

```{r}
#Filter 3Room, 4Room, 5Room
HDBRoom <- HDB %>% filter(flat_type=="3 ROOM" | flat_type=="4 ROOM" | flat_type=="5 ROOM") %>%
  separate(month, into = c("year", "month")) %>% 
  filter(year == "2022") %>%
  separate(remaining_lease, into = c("rmlease_years", "rmlease_month"), sep = "years") 

HDBRoom$rmlease_years <- as.numeric(HDBRoom$rmlease_years)

HDBRoom$rmlease_month <- gsub("[monthsmonth]", " ", HDBRoom$rmlease_month) %>%
  as.numeric(HDBRoom$rmlease_month) / 12 

HDBRoom

```

```{r}
HDBRoom$storey_range <- factor (HDBRoom$storey_range, levels = unique(HDBRoom$storey_range))
ggplot(data = HDBRoom,
  aes(x =storey_range)) + geom_bar()

```

```{r}
unique(HDBRoom$storey_range)
```

```{r}

HDBRoom$rmlease_month[is.na(HDBRoom$rmlease_month)] = 0

HDBRoom$rmlease <- as.numeric(HDBRoom$rmlease_years + HDBRoom$rmlease_month)

HDBRoom$storey_range <- str_replace(HDBRoom$storey_range, "TO", "-")

rep_sr = c(
  "22 - 24"="> 21", 
  "25 - 27"="> 21", 
  "28 - 30"="> 21",
  "31 - 33"="> 21",
  "34 - 36"="> 21", 
  "37 - 39"="> 21", 
  "40 - 42"="> 21", 
  "43 - 45"="> 21", 
  "49 - 51"="> 21", 
  "46 - 48"="> 21"
  )

HDBRoom$storey_range <- str_replace_all(HDBRoom$storey_range, rep_sr)

sr_sort = c("01 - 03", "04 - 06", "07 - 09", "10 - 12", "13 - 15", "16 - 18", "19 - 21", "> 21")

HDBRoom$storey_range <- factor (HDBRoom$storey_range, levels = sr_sort)

ggplot(data = HDBRoom,
  aes(x =storey_range)) + geom_bar()
```

```{r}
HDBDATA <- HDBRoom [,!names(HDBRoom) %in% c("year", "block", "street_name", "rmlease_years", "rmlease_month", "flat_model")]

HDBDATA
```

```{r}
gghistostats(
  data = HDBDATA, x = "floor_area_sqm",
  type = "bayes",
  test.value = 100,
  xlab = "Floor Area (sqm) of property sold"
  )
```

```{r}
ggbetweenstats(
  data = HDBDATA,
  x = flat_type, 
  y = price_per_sqm,
  type = "np",
  messages = FALSE
)
```

```{r}
plot_ly(data = HDBDATA, 
        x = ~price_per_sqm, 
        y = ~storey_range,
        text = ~paste("Town:", town,     
                      "<br>Remaining Lease in years:", rmlease),  
        color = ~flat_type, 
        colors = "Set1") %>%
  layout(title = 'Price per Sqm vs Flat storey ')
```

```{r}
ggscatterstats(
  data = HDBDATA,
  x = resale_price,
  y = rmlease,
  marginal = FALSE,
  )
```

```{r}
o
ggplot(data = HDBDATA,
       aes(y = town,
           x = price_per_sqm)) + 
  geom_boxplot()
```
